name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Run Prettier
        run: npx --yes prettier --check .
