name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Run Prettier
        run: npx --yes prettier --check .
